kind: pipeline
name: default

steps:
- name: build
  image: node
  volumes:
  - name: artifacts
    path: /tmp/artifacts
  commands:
  - npm install
  - npm run build
  - cp build/userscript/github-repo-size.user.js /tmp/artifacts/github-repo-size.user.js
  - cp build/webext-dist/github-repo-size.zip /tmp/artifacts/github-repo-size.zip
- name: publish
  image: plugins/github-release
  volumes:
  - name: artifacts
    path: /tmp/artifacts
  settings:
    api_key:
      from_secret: github_token
    files: /tmp/artifacts
  when:
    event: tag

volumes:
- name: artifacts
  temp: {}