version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
      - store_artifacts:
          path: build/userscript/github-repo-size.user.js
          destination: userscript
      - store_artifacts:
          path: build/webext-dist/github-repo-size.zip
          destination: webext
      - persist_to_workspace:
          root: /tmp/artifacts
          paths: 
            - build/userscript/github-repo-size.user.js
            - build/webext-dist/github-repo-size.zip

  release:
    docker:
      - image: cibuilds/github:0.12
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: |
          mkdir uploads &&
          cp ./artifacts/build/userscript/github-repo-size.user.js uploads/github-repo-size.user.js &&
          cp ./artifacts/build/webext-dist/github-repo-size.zip uploads/github-repo-size.zip
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -recreate ${CIRCLE_TAG} ./uploads/

workflows:
  version: 2
  main:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
