name: Release

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # cache dependencies
      - name: Get yarn cache directory
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "Cache: yarn"
        uses: actions/cache@v1.1.2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Use Node.js 12.10
        uses: actions/setup-node@v1
        with:
          node-version: "12.10"
          registry-url: "https://npm.pkg.github.com"

      - run: yarn install --pure-lockfile

      - run: yarn build

      - name: Upload Webext Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/webext-dist/github-repo-size.zip
          asset_name: github-repo-size.zip
          asset_content_type: application/zip
      - name: Upload Userscript Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/userscript/github-repo-size.user.js
          asset_name: github-repo-size.user.js
          asset_content_type: application/javascript